### PR TITLE
Updated snippets (4.0.0-beta)

### PR DESCRIPTION
**Pull request by wolnyludz**
I've converted Sublime Text snippets[1] with linux sed command and atomizr[2]. The directories structure have changed a lot but it seems to work.

[1] https://github.com/degouville/sublime-bootstrap4
[2] https://github.com/idleberg/node-atomizr

### CODE REVIEW

**Comment by degouville** [comment]
@wolnyludz look great! good job 👏

**Comment by degouville** [comment]
can i mention about u in the readme?

**Comment by wolnyludz** [comment]
Sure. Thanks.

**Comment by wolnyludz** [comment]
Just in case if there were more snippets in the future to convert.
```
//With terminal opened in the snippets folder.
sed -i "s/<\/snippet>/<scope>text.html<\/scope><\/snippet>/g" *
find ./ -type f -exec atomizr "*" -t atom -o ~/.atom/packages/atom-bootstrap4/snippets/a.cson {} \;
```

**Comment by wolnyludz** [comment]
Oh wait. I forgot to put these converted files into snippets directory after deleting everything inside.
It should be
```
-atom-screenshot
-settings
-snippets
|-a.cson
|-accordion.cson
|-...
```

**Pull request merged**
